### ISSUE TITLE
| ERROR] Cash App emoji was not found. The emoji must be named "cashapp"

### ISSUE THREAD

**Issue by monkeycoder-max** [FivePixels/Tribble#1]
Hello i keep getting this error i tried to go into the code to check but all looks good ! Do you know where i can refer to fix this?

**Comment by monkeycoder-max** [comment]
oh by the way this is an awesome bot !

**Comment by FivePixels** [comment]
I forgot that I didn't complete the implementation for this section of the code. I removed it from the source in
the https://github.com/FivePixels/Tribble/commit/06b41eb45219be38cd8f4a283a347c44222d9a96 commit. I will consider completing implementation later. Thank you for the compliment!
