### ISSUE TITLE
Move to discord.js-menu-buttons

### ISSUE THREAD

**Issue by FivePixels** [FivePixels/Tribble#13]
discord.js-menu is no longer being maintained. To move forward with the trend of Discord using buttons instead of reactions, we should use discord.js-menu-buttons as a dependency instead. This task is to rewrite the entire menu setup to use discord.js-menu-buttons syntax, which is much different than the syntax of discord.js-menu.

https://github.com/kalempster/discord.js-menu-buttons

**Comment by 2M4U** [comment]
Hey, I'm enquiring on how long this would take as I'm wanting to use this src, and I have attempted to update `discord.js-menu` to v14 or so but it still bugs out *haha*.
Kind Regards, 2G

**Comment by FivePixels** [comment]
> Hey, I'm enquiring on how long this would take as I'm wanting to use this src, and I have attempted to update `discord.js-menu` to v14 or so but it still bugs out _haha_. Kind Regards, 2G

Right now there's no official timeline. I want to get #12 in first, but this may come simultaneously since discord.js-menu seems to be broken in current state.

**Comment by FivePixels** [comment]
As part of this issue I'm updating to slash commands as well.

**Comment by FivePixels** [comment]
Update: I'm getting close to finals week at my college now, so I won't be able to put time into this for the next few weeks.

**Comment by FivePixels** [comment]
Right now we're waiting on my PR in the discord.js-menu-buttons repo to be approved and merged. There's a bug that will cause ticket issues if not resolved.
https://github.com/kalempster/discord.js-menu-buttons/pull/3

**Comment by FivePixels** [comment]
Forgot to tag it, but here's another commit. Currently we're in a holding pattern until these two PRs land:
https://github.com/kalempster/discord.js-menu-buttons/pull/7
https://github.com/kalempster/discord.js-menu-buttons/pull/8

**Comment by FivePixels** [comment]
The only thing left here is to update the `config.json` format to give users a format when configuring their bot. After that, I'd say this enhancement is good to merge.
