### ISSUE TITLE
URIError: URI malformed

### ISSUE THREAD

**Issue by kanetjuh** [FivePixels/Tribble#16]
This happens after I open the payment ticket and press the agree emoji/button.
![image](https://user-images.githubusercontent.com/50002439/204483752-9baf96b6-3cb1-4f9e-bdae-d96c8938089c.png)

**Comment by kanetjuh** [comment]
Note: This happens when I disable the TOS, and make a new ticket.
![image](https://user-images.githubusercontent.com/50002439/204484378-1c01bead-b402-4193-b9f7-c455b5bfb299.png)

**Comment by FivePixels** [comment]
Yep, this is due to discord.js-menu not supporting the latest version of discord.js and Discord's new endpoint URIs. This will be fixed with #13.

**Comment by FivePixels** [comment]
@kanetjuh #13 has been resolved. Will be closing this issue if it cannot be reproduced.
