### ISSUE TITLE
Payment verification not working.

### ISSUE THREAD

**Issue by kanetjuh** [FivePixels/Tribble#17]
![image](https://user-images.githubusercontent.com/50002439/204489871-b4ad6c75-e1a1-4b8b-aa7b-16fc923efdc2.png)
I've tried everything but it doesn't verify that the payment has gone through while it did.
- And yes I added the Google credentials et cetera.

**Comment by FivePixels** [comment]
Can you send the log after you perform the search?

**Comment by kanetjuh** [comment]
What do you mean by `the search`?

**Comment by kanetjuh** [comment]
![image](https://user-images.githubusercontent.com/50002439/204747884-3d65d333-b1ae-4402-85d6-033b5af96a8f.png)
Yesterday when I got this several times I only got this in the logs.

**Comment by 2M4U** [comment]
@kanetjuh Can you specify which "payment" method you used, as the layout sent from them _may have_ changed.

**Comment by kanetjuh** [comment]
I used paypal

**Comment by FivePixels** [comment]
@kanetjuh Can you try to reproduce this issue to see if it's still valid?
