### ISSUE TITLE
Bugs? 🐛🐛🐛

### ISSUE THREAD

**Issue by 2M4U** [FivePixels/Tribble#18]
Hey found a few bug's on the new src;

`config.PRODUCTS_EMOJIS.split(',');` referenced [Line 10 on /pages/products/ProductsPage.js](https://github.com/FivePixels/Tribble/blob/13-move-to-discordjs-menu-buttons/pages/products/ProductsPage.js#L10)

There is more, some like `dev.json` being defined specifically instead of checking for `config.json` over `dev.json`, which I assume your aware of because it seems intentional for dev purposes(?)

**Comment by FivePixels** [comment]
Yes I'm aware. I'm not done implementing all of the changes yet. Once #13 merged into main it'll be clear I'm finished.
