### ISSUE TITLE
[Issue] TOS/Product/Payment Page

### ISSUE THREAD

**Issue by 2M4U** [FivePixels/Tribble#23]
With the config `ENABLE_TOS` set to `false`, the bot works as intended (not tested payment validation as yet), however when the config `ENABLE_TOS` is set to `true`, it bugs the bot out and does a repeating pattern between TOSPage & ProductPage, it never reaches payment page.

**Comment by FivePixels** [comment]
I have `ENABLE_TOS` set to true as well, but my bot doesn't get into a repeating pattern. Can you share your configuration?

**Comment by FivePixels** [comment]
Should be resolved, closing this issue - feel free to reopen if the issue is still occurring.
