### ISSUE TITLE
more amount option

### ISSUE THREAD

**Issue by DEIVUXO1** [FivePixels/Tribble#6]
make that you could pay for more amount like product with 1euro cost and product with 3euro cost because it only allows 1 amount of money

**Comment by FivePixels** [comment]
So this is a larger ask, and may take some time to develop. Here are some of my thoughts:

- Implement Tribble to operate like a "shop".
   - The configuration could have entries for the products and their prices, however Tribble doesn't currently support adding product names. Currently, the implementation assumes the user is greeted with a message in the panel saying "To buy Product A, react here", and you purchase one of the product.  This will need to be written in and a menu to select the item for purchase will need to be written as well.
   - This ask will make Tribble operate like a shop - however I don't see any issues with that. In fact, right now you'd need to run more than one instance of Tribble to get this same sort of "shop" effect in your server. 
   - This ask can definitely be achieved with some work. It will take time to develop though. I may be able to work on this in the next month or two.
