### ISSUE TITLE
How to start

### ISSUE THREAD

**Issue by azurexxxx** [FivePixels/Tribble#8]
Hey! I did every single step in your guides and followed each and everyone of them carefully. I have completed the setup and installation process but I can't seem to find the correct command to start the bot. I tried `node index.js` but it doesn't work. Could you help, please?
![image](https://user-images.githubusercontent.com/71032889/189486012-46ba76da-4721-4fbd-a5b7-7f6937ee9296.png)

**Comment by FivePixels** [comment]
Could you try running `node .` in the root directory of the project?

**Comment by azurexxxx** [comment]
![image](https://user-images.githubusercontent.com/71032889/192089525-ef08fbc1-cddd-411d-b9aa-719dd2c83b2c.png)
Sorry for the late reply.

**Comment by FivePixels** [comment]
Make sure you have yarn installed, then run `yarn install` in the root directory of the project. Let me know if that works.

**Comment by FivePixels** [comment]
I'm closing this issue as I haven't heard back in close to 3 weeks.
